### ISSUE TITLE
Pixi v5 support

### ISSUE THREAD

**Issue by getkey** [eXponenta/gstatsjs#4]
Hey @eXponenta!

I just added Pixi v5 support to [my fork](getkey/gstatsjs). Maybe I'll get around sending a PR your way later, if I don't, I still want to share how to you.
It's just a matter of changing a couple lines (see https://github.com/getkey/gstatsjs/commit/a2e24882a6bd0d12c3fc273a6a7ad967f7fb47ac).

**Comment by eXponenta** [comment]
You can send PR in other branch, named as pixiv5, because v4 more populare at the moment.
But I'm use v5 too.

**Comment by getkey** [comment]
It's possible to support both. :slightly_smiling_face: 
I just didn't do it because since I use only v5 I don't want to go through the trouble of testing it on v4.

**Comment by eXponenta** [comment]
Ok.
Send me PR, and then i fix it for hybrit support (v5 and v4)
