### ISSUE TITLE
Details about DrawPasses

### ISSUE THREAD

**Issue by AdrienLemaire** [eXponenta/gstatsjs#8]
Sorry for the newbie question, I'm new to game development.
I've learnt about draw calls (calling an opengl draw function), and the acronym that you use in the custom panel is DC. 
Is that correct that DrawPasses = Draw calls here ?

I'm currently testing with 2 textures (a map and a character). The character can move on the map with a viewport following it (culling enabled).
When moving my character, I'm expecting the DC value to change, but it's always set to 1.

Is that a bug in gstatsjs ?

Demo [here](https://youtu.be/B02GDsywb1) (or click on the image):
<a href="https://youtu.be/B02GDsywb1s"><img src="https://i9.ytimg.com/vi/B02GDsywb1s/mq1.jpg?sqp=CKzZlP8F&rs=AOn4CLCuU_uB2zyxIHTCOcClv57KSr_Mug" /></a>

<details><summary>my implementation of gstatsjs</summary>

```tsx
// eslint-disable-next-line import/no-extraneous-dependencies
import Stats from "stats.js";
import React, { useEffect, useMemo } from "react";
// @ts-ignore
import { PIXIHooks, StatsJSAdapter } from "gstats";
import { useApp, useTick } from "@inlet/react-pixi";

// @ts-ignore gross, but needed by gstat
window.Stats = Stats;

/** @SR
 * development env only component to show FPS/RAM/GRAM stats
 *
 * FPS: Frames rendered in the last second. The higher the number the better.
 * MS:  Milliseconds needed to render a frame. The lower the number the better.
 * MB:  MBytes of allocated memory. (Run Chrome with --enable-precise-memory-info)
 * DC: DrawPasses
 * TC: Texture count
 */
const DebugStatsView: React.FC = () => {
  const app = useApp();
  const stats = useMemo(() => new StatsJSAdapter(new PIXIHooks(app)), [app]);

  useTick(() => stats?.update());
  useEffect(() => {
    const domElement = stats.stats.dom || stats.stats.domElement;
    domElement.style.top = "";
    domElement.style.bottom = "0px";
    return stats.stats && document.body.appendChild(domElement);
  }, [stats.stats]);
  return null;
};

export default DebugStatsView;
```

</details>

**Comment by eXponenta** [comment]
DC track a gl.drawElements command, it maybe be less that real used, but not a greater if update is called, PIXI v4 use only drawElements, need check how it works on v5.
`useTick` should be invoked after render pass every render, otherwise it will be delayed on frame.

https://github.com/eXponenta/gstatsjs/blob/master/src/GLHook.ts#L20

**Comment by AdrienLemaire** [comment]
Right, I'm using Pixi v5.

A [grep for gl.draw](https://github.com/pixijs/pixi.js/search?q=gl.draw) returns calls to gl.drawElements, drawBuffersWEBGL, drawElementsInstanced and drawArraysInstanced.

> useTick should be invoked after render pass every render, otherwise it will be delayed on frame.

I'm not sure how to verify this.
I've added `useTick(() => stats?.update());` to my component.
That means [app.ticker](https://github.com/inlet/react-pixi/blob/4dbbbc91a5bd143770f93e6b9d996d8f53cf766b/src/hooks/useTick.js#L26)   will [add the stats.update function](https://github.com/pixijs/pixi.js/blob/efad52f8e24513b7566b2e2b743d8e07580b911b/packages/ticker/src/Ticker.ts#L262) with a ticker listener, and [start it](https://github.com/pixijs/pixi.js/blob/efad52f8e24513b7566b2e2b743d8e07580b911b/packages/ticker/src/Ticker.ts#L389)

> Starts the ticker. If the ticker has listeners a new animation frame is requested at this point.

I can't tell by reading the code if my tick is delayed on frame or not, but it's a fact that DC always return 1 for value and nothing else.

> https://github.com/eXponenta/gstatsjs/blob/master/src/GLHook.ts#L20

I can confirm that GL is Hooked in my app.
![](https://i.imgur.com/SKBU0yx.png)

Please let me know if you'd like me to try something if that can help :handshake:

**Comment by eXponenta** [comment]
PixiJS use aggressive batching, and 20 or more elements can be rendered per 1 DC.
We cannot handle this behaviour, because only render buffer will he changed when batchable object is culled.

i render a 2000+ shapes in single DC :)
https://exponenta.games/games/map
